apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-server-block
  labels:
    app.kubernetes.io/name: nginx-svr
    helm.sh/chart: nginx-svr-1.0.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
data:
  server-blocks-paths.conf: |-
    include  "/opt/bitnami/nginx/conf/server_blocks/ldap/*.conf";
    include  "/opt/bitnami/nginx/conf/server_blocks/common/*.conf";
  server-block.conf: |-
    server {
      listen 8080;
      # server_name  spayh5.wjkfs.hnnxs.com;

      client_max_body_size 80M;

      location /webapp {
          root /app;
          try_files $uri $uri  /webapp/index.html;
      } 
      location /spayh5 {
          alias            /app/spayh5;
      }
      location /spay {
		    proxy_set_header X-Scheme $scheme;
		    proxy_set_header Host $host;
		    proxy_set_header X-Forwarded-Proto $scheme;
		    proxy_set_header X-Real-IP $remote_addr;
		    proxy_pass http://10.12.169.13:8080;
      }
    }